name: GameOfLife
version: '1.0'
main: me.ominous.gameoflife.GameOfLife
api-version: '1.20'
commands:
  start-life:
    description: Starts the game of life
  reset-life:
    description: Resets the game